input number + star
charlottecgd/eurom pull request #1
Opened 2024-07-17 14:58 UTC by charlottecgd

2024-07-17 15:16 UTC, kevin-sennoun-lapala requested changes

2024-07-17 15:16 UTC, kevin-sennoun-lapala commented on eurom/src/app/globals.css
On ne laisse pas de code désactivé, si pas besoin du bloc il faut le supprimer

2024-07-17 15:16 UTC, kevin-sennoun-lapala commented on eurom/src/app/page.tsx
> +  const handleNumbersInputChange = (e: any) => {
t'es sûre que any est justifié ici ?

2024-07-17 15:16 UTC, kevin-sennoun-lapala commented on eurom/src/app/page.tsx
> +  const [numbers, setNumbers] = useState<number[]>([]); // État pour stocker les 5 numéros après validation.
utilité ?

2024-07-17 15:16 UTC, kevin-sennoun-lapala commented on eurom/src/app/page.tsx
> +  const [numbers, setNumbers] = useState<number[]>([]); // État pour stocker les 5 numéros après validation.
pourquoi différencier les nombres saisies dans l'input des nombres tout court ? Surtout que dans ton code, dès que l'un change l'autre aussi, donc t'as juste la donnée en double

2024-07-17 15:18 UTC, charlottecgd commented on eurom/src/app/page.tsx
> +  const handleNumbersInputChange = (e: any) => {
es-lint mettait en rouge

2024-07-17 15:19 UTC, charlottecgd commented on eurom/src/app/page.tsx
> +  const handleNumbersInputChange = (e: any) => {
<img width="549" alt="image" src="https://github.com/user-attachments/assets/d0c031d3-9549-4b02-b7a4-f65e8b0897e3">

2024-07-17 15:54 UTC, kevin-sennoun-lapala requested changes

2024-07-17 15:54 UTC, kevin-sennoun-lapala commented on eurom/src/app/globals.css
> +/* :root {
code désactivé qui ne sert a rien

2024-07-17 16:19 UTC, kevin-sennoun-lapala commented on eurom/src/app/page.tsx
> +  const handleNumbersInputChange = (e: any) => {
Oui mais any c'est pas une bonne pratique, ça veut dire "n'importe quel type", ce qui veut dire que c'est comme si y'avait pas de TS. Il faut trouver le bon type à utiliser surtout.

2024-07-17 16:21 UTC, kevin-sennoun-lapala commented on eurom/src/app/page.tsx
> +  const handleNumbersInputChange = (e: any) => {
https://stackoverflow.com/questions/40676343/typescript-input-onchange-event-target-value

2024-07-19 12:36 UTC, kevin-sennoun-lapala approved these changes

2024-07-19 12:36 UTC, merged